### ISSUE TITLE
Issues from abandoned iitc-project

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#123]
Feature Requests:
- [ ] Draw without creating crosslinks [#1267](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1267)
- [ ] Add open location code search [#1218](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1218)
- [ ] Show vanilla intel plans on temporary layer [#1197](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1197)
- [ ] Language Support for Arabic and Hebrew [#1200](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1200)
- [ ] Optional portals/function parameter for window.plugin.portalcounts.getPortals [#1171](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1171)
- [ ] Sort "Missions in view" list [#1130](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1130)
- [ ] Mission Filtering [#1082](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1082)
- [ ] Dialog location isn't remembered [#1104](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1104)
- [ ] sync drawn items [#1030](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1030)
- [ ] Add tooltip to player name in portal details view [#1078](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1078)
- [ ] Cache Key Locations [#1039](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1039)
- [ ] Undo for "Snap to Portas" [#1052](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1052)
- [ ] chat and chatcontrols toggle [#1016](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1016)
- [ ] Letting distance to portal plugin use Lat/lng searched for [#996](https://github.com/iitc-project/ingress-intel-total-conversion/issues/996)
- [ ] New color on markedStarterPortals in missions plugin [#989](https://github.com/iitc-project/ingress-intel-total-conversion/issues/989)
- [ ] add-kml: load file from url (web) /improvement request/ [#988](https://github.com/iitc-project/ingress-intel-total-conversion/issues/988)
- [ ] Portal display filtering [#962](https://github.com/iitc-project/ingress-intel-total-conversion/issues/962)
- [ ] Bookmarks Suggestion Tags instead of Folders [#912](https://github.com/iitc-project/ingress-intel-total-conversion/issues/912)
- [ ] Software back button for mobile info page [#904](https://github.com/iitc-project/ingress-intel-total-conversion/issues/904)
  - Map button https://github.com/dossy/ingress-intel-total-conversion/blob/plugin-toolbox-show-map-button/plugins/toolbox-show-map-button.user.js (https://gist.github.com/dossy/37018a19099f0174f3bd1220fd7f3354) ([install](https://git.io/vimBB))
- [ ] Show installed plugins on download page [#610](https://github.com/iitc-project/ingress-intel-total-conversion/issues/610)
- [ ] Max links: make an option to only show linkable links for the current state [#719](https://github.com/iitc-project/ingress-intel-total-conversion/issues/719)
- [ ] Fly links plugin [#736](https://github.com/iitc-project/ingress-intel-total-conversion/issues/736)
  - [ ] manually select portals for Fly Links/Fly Fields plugin [#852](https://github.com/iitc-project/ingress-intel-total-conversion/issues/852)
  - [ ] Exclude portals from Fly Links [#803](https://github.com/iitc-project/ingress-intel-total-conversion/issues/803)
  - [ ] ignoring selected portals, and not showing it on the map [#1096](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1096)
- [ ] Draw Tools and GeoJSON [#873](https://github.com/iitc-project/ingress-intel-total-conversion/issues/873)
- [ ] Add iOS installation via bookmarklet [#833](https://github.com/iitc-project/ingress-intel-total-conversion/issues/833)
- [ ] There should be a setting panel in IITC [#239](https://github.com/iitc-project/ingress-intel-total-conversion/issues/239)
  - [ ] Plugin: MaxLinks, possible to stop it recalculating on zoom? [#340](https://github.com/iitc-project/ingress-intel-total-conversion/issues/340)
- [ ] Improved updating of map data using COMM messages [#825](https://github.com/iitc-project/ingress-intel-total-conversion/issues/825)
- [ ] Every time a link is shown on the comm/log, show the distance as well [#804](https://github.com/iitc-project/ingress-intel-total-conversion/issues/804)
- [ ] Multi Select Portal Link Draw [#773](https://github.com/iitc-project/ingress-intel-total-conversion/issues/773)
- [ ] Possible linking area [#771](https://github.com/iitc-project/ingress-intel-total-conversion/issues/771)
- [ ] File save/load plugin [#751](https://github.com/iitc-project/ingress-intel-total-conversion/issues/751)
- [ ] Update map data from data returned by getPortalDetails [#758](https://github.com/iitc-project/ingress-intel-total-conversion/issues/758)
  - Detailed portal data mismatch vs summary data [#674](https://github.com/iitc-project/ingress-intel-total-conversion/issues/674)
  - Example data we have for all portals: https://github.com/iitc-project/ingress-intel-total-conversion/issues/668
- [ ] introduce color schemes [#732](https://github.com/iitc-project/ingress-intel-total-conversion/issues/732)
- [ ] Portal link possibility [#686](https://github.com/iitc-project/ingress-intel-total-conversion/issues/686)
- [ ] Plugin: show local timezome (and other data?) [#708](https://github.com/iitc-project/ingress-intel-total-conversion/issues/708)
- [ ] Mark upgradable Resonators and missing Mods in the portal detail view [#714](https://github.com/iitc-project/ingress-intel-total-conversion/issues/714)

**Comment by johnd0e** [comment]
Bugs:
- [ ] IITC does not show a link, that exists [#1195](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1195)
- [ ] IITC mobile doesn't handle HTTP Statuscode 301 on installing plugins [#1092](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1092)
- [ ] Bug in cross links [#1085](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1085)
- [ ] deploying a mod does not count as visit anymore [#1083](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1083)
- [ ] Small inaccuracies in drawn lines, compared to stock [#1011](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1011)
- [ ] Long links not represented the same as stock intel [#629](https://github.com/iitc-project/ingress-intel-total-conversion/issues/629)
- [ ] Bookmark + Sync plugins: Fix bookmarks sort order [#1013](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1013)
- [ ] COMMS data is significantly outdated [#902](https://github.com/iitc-project/ingress-intel-total-conversion/issues/902)
- [ ] Outgoing/ingoing links are counted wrong [#1009](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1009)
- [ ] plugin Overlay KML -> no geodesic polyline! [#805](https://github.com/iitc-project/ingress-intel-total-conversion/issues/805)
- [ ] field covering north pole not rendered correctly [#786](https://github.com/iitc-project/ingress-intel-total-conversion/issues/786)

Not checked:
- [ ] Sort Uniques by Visit does not work on some portals [#1143](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1143)
- [ ] Fails to delete portals by bounds [#1149](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1149)
- [ ] Sync plugin account change [#1095](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1095)
- [ ] Invalid range calculation for portals with level of <1 [#794](https://github.com/iitc-project/ingress-intel-total-conversion/issues/794)
- [ ] Todo: update low-level network requests to be friendlier to the servers, especially in error situations [#776](https://github.com/iitc-project/ingress-intel-total-conversion/issues/776)

**Comment by johnd0e** [comment]
Other:
 - Question: How to add button on top left leaflets of controls? [#1147](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1147)
- The real bottleneck is how we are writing to localstorage: https://github.com/iitc-project/ingress-intel-total-conversion/issues/1149#issuecomment-276983389
- Draw Tools Error: The specified value "!" does not conform to the required format [#1151](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1151)
- Uncaught TypeError: L is not a constructor [#1162](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1162)
- IITCm runs plugin scripts before main script [#1172](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1172)
- Links lost after data refresh with zoom change [#795](https://github.com/iitc-project/ingress-intel-total-conversion/issues/795)
- File opening from JS - allow mime type to be specified [#792](https://github.com/iitc-project/ingress-intel-total-conversion/issues/792)
- Add internal limits on portalDetail.request? [#779](https://github.com/iitc-project/ingress-intel-total-conversion/issues/779)
- Fonts
  - Could you make a option for changing font? [#1090](https://github.com/iitc-project/ingress-intel-total-conversion/issues/1090)
  - CSS and Web Font fixes [#602](https://github.com/iitc-project/ingress-intel-total-conversion/pull/602)
  - non-english characters not displayed [#541](https://github.com/iitc-project/ingress-intel-total-conversion/issues/541)
